spring:
  application:
    name: tpiuc

  datasource:
    url: jdbc:postgresql://localhost:5432/tpiuc_db
    username: postgres
    password: Wilfried23
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

    show-sql: true

    # Pour éviter les problèmes de performance et de LazyInitialization
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

    # database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080