package com.iuc.tpiuc.audit;

public enum AuditActions {

    CREATION_SALLE,
    MODIFICATION_SALLE,
    RECHERCHE_SALLE_PAR_IDENTIFIANT,
    LISTE_DES_SALLES,
    SUPPRESSION_SALLE,

    CREATION_MATERIEL,
    MODIFICATION_MATERIEL,
    RECHERCHE_MATERIEL_PAR_IDENTIFIANT,
    LISTE_DES_MATERIELS,
    SUPPRIMER_UN_MATERIEL,

    CREATION_RESERVATION,
    MODIFICATION_STATUT_RESERVATION,
    RECHERCHE_RESERVATION_PAR_IDENTIFIANT,
    RECHERCHE_RESERVATION_PAR_PROFESSEUR,
    LISTE_DES_RESERVATIONS,
    SUPPRIMER_RESERVATION,
    
    CREATION_UTILISATEUR,

    CREATION_SIGNALEMENT

}
