package com.iuc.tpiuc.audit;

public enum AuditActions {

    CREATION_SALLE,
    MODIFICATION_SALLE,
    RECHERCHE_SALLE_PAR_IDENTIFIANT,
    LISTE_DES_SALLES,
    SUPPRESSION_SALLE,
    MODIFICATION_STATUT_SALLE,
    LISTER_SALLES_PAR_DISPONIBILITE,

    CREATION_MATERIEL,
    MODIFICATION_MATERIEL,
    RECHERCHE_MATERIEL_PAR_IDENTIFIANT,
    LISTE_DES_MATERIELS,
    SUPPRIMER_MATERIEL,
    MODIFICATION_ETAT_MATERIEL,
    LISTER_MATERIELS_PAR_ETAT,


    CREATION_RESERVATION,
    MODIFICATION_STATUT_RESERVATION,
    RECHERCHE_RESERVATION_PAR_IDENTIFIANT,
    RECHERCHE_RESERVATION_PAR_PROFESSEUR,
    LISTE_DES_RESERVATIONS,
    SUPPRIMER_RESERVATION,
    DEMARRER_COURS,
    VALIDATION_CAHIER_TEXTE,

    CREATION_UTILISATEUR,
    MODIFICATION_UTILISATEUR,
    RECHERCHE_UTILISATEUR_PAR_IDENTIFIANT,
    LISTE_DES_UTILISATEURS,
    DESACTIVER_UTILISATEUR,
    ACTIVER_UTILISATEUR,
    CONSULTER_PROFIL_UTILISATEUR,
    MODIFIER_PROFIL_UTILISATEUR,
    MODIFIER_MOT_DE_PASSE_UTILISATEUR,
    CONNEXION_UTILISATEUR,
    DECONNEXION_UTILISATEUR,


    CREATION_SIGNALEMENT,
    MODIFICATION_SIGNALEMENT,
    RECHERCHE_SIGNALEMENT_PAR_IDENTIFIANT,
    LISTER_LES_SIGNALEMENTS,
    RECHERCHE_SIGNALEMENTS_PAR_CREATEUR,
    RECHERCHE_SIGNALEMENTS_PAR_MATERIEL,
    RECHERCHE_SIGNALEMENTS_PAR_CREATEUR_ET_MATERIEL,
    RECHERCHE_SIGNALEMENT_PAR_DATES,
    SUPPRESSION_SIGNALEMENT

}
