package com.iuc.tpiuc.audit;

public enum AuditActions {

    CREATION_SALLE,
    MODIFICATION_SALLE,
    SUPPRESSION_SALLE,

    CREATION_MATERIEL,
    MODIFICATION_MATERIEL,
    RECHERCHE_MATERIEL_PAR_IDENTIFIANT,
    LISTE_DES_MATERIELS,
    SUPPRIMER_UN_MATERIEL,

    CREATION_RESERVATION,
    VALIDATION_RESERVATION,
    REFUS_RESERVATION,

    CREATION_UTILISATEUR,

    CREATION_SIGNALEMENT

}
